//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace RuRo.Web.QueryRecoder {
    
    
    /// <summary>
    /// Add 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Add 
    {
        
		protected global::System.Web.UI.WebControls.TextBox txtUname;
		protected global::System.Web.UI.WebControls.TextBox txtAddDate;
		protected global::System.Web.UI.WebControls.TextBox txtLastQueryDate;
		protected global::System.Web.UI.WebControls.TextBox txtCode;
		protected global::System.Web.UI.WebControls.TextBox txtCodeType;
		protected global::System.Web.UI.WebControls.TextBox txtQueryType;
		protected global::System.Web.UI.WebControls.TextBox txtQueryResult;
		protected global::System.Web.UI.WebControls.CheckBox chkIsDel;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
