//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace RuRo.Web.QueryRecoder {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblId;
	protected global::System.Web.UI.WebControls.Label lblUname;
	protected global::System.Web.UI.WebControls.Label lblAddDate;
	protected global::System.Web.UI.WebControls.Label lblLastQueryDate;
	protected global::System.Web.UI.WebControls.Label lblCode;
	protected global::System.Web.UI.WebControls.Label lblCodeType;
	protected global::System.Web.UI.WebControls.Label lblQueryType;
	protected global::System.Web.UI.WebControls.Label lblQueryResult;
	protected global::System.Web.UI.WebControls.Label lblIsDel;


       
    }
}
