//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18408
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace RuRo.BLL.GetQueryPT {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://chas.hit.com/transport/integration/common/intf", ConfigurationName="GetQueryPT.ChasCommonPT")]
    public interface ChasCommonPT {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://chas.hit.com/transport/integration/common/intf/queryPatient", ReplyAction="*")]
        [System.ServiceModel.DataContractFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="queryPatientResponse")]
        string queryPatient(string queryPatientRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://chas.hit.com/transport/integration/common/intf/queryDiagnosis", ReplyAction="*")]
        [System.ServiceModel.DataContractFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="queryDiagnosisResponse")]
        string queryDiagnosis(string queryDiagnosisRequest);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ChasCommonPTChannel : RuRo.BLL.GetQueryPT.ChasCommonPT, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ChasCommonPTClient : System.ServiceModel.ClientBase<RuRo.BLL.GetQueryPT.ChasCommonPT>, RuRo.BLL.GetQueryPT.ChasCommonPT {
        
        public ChasCommonPTClient() {
        }
        
        public ChasCommonPTClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ChasCommonPTClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ChasCommonPTClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ChasCommonPTClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string queryPatient(string queryPatientRequest) {
            return base.Channel.queryPatient(queryPatientRequest);
        }
        
        public string queryDiagnosis(string queryDiagnosisRequest) {
            return base.Channel.queryDiagnosis(queryDiagnosisRequest);
        }
    }
}
