//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace RuRo.Web.NormalLisReport {
    
    
    /// <summary>
    /// Modify 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Modify {
        	protected global::System.Web.UI.WebControls.Label lblId;
		protected global::System.Web.UI.WebControls.TextBox txthospnum;
		protected global::System.Web.UI.WebControls.TextBox txtpatname;
		protected global::System.Web.UI.WebControls.TextBox txtSex;
		protected global::System.Web.UI.WebControls.TextBox txtAge;
		protected global::System.Web.UI.WebControls.TextBox txtage_month;
		protected global::System.Web.UI.WebControls.TextBox txtext_mthd;
		protected global::System.Web.UI.WebControls.TextBox txtchinese;
		protected global::System.Web.UI.WebControls.TextBox txtresult;
		protected global::System.Web.UI.WebControls.TextBox txtunits;
		protected global::System.Web.UI.WebControls.TextBox txtref_flag;
		protected global::System.Web.UI.WebControls.TextBox txtlowvalue;
		protected global::System.Web.UI.WebControls.TextBox txthighvalue;
		protected global::System.Web.UI.WebControls.TextBox txtprint_ref;
		protected global::System.Web.UI.WebControls.TextBox txtcheck_date;
		protected global::System.Web.UI.WebControls.TextBox txtcheck_by_name;
		protected global::System.Web.UI.WebControls.TextBox txtprnt_order;
		protected global::System.Web.UI.WebControls.CheckBox chkIsDel;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
