//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace RuRo.Web.NormalLisReport {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblId;
	protected global::System.Web.UI.WebControls.Label lblhospnum;
	protected global::System.Web.UI.WebControls.Label lblpatname;
	protected global::System.Web.UI.WebControls.Label lblSex;
	protected global::System.Web.UI.WebControls.Label lblAge;
	protected global::System.Web.UI.WebControls.Label lblage_month;
	protected global::System.Web.UI.WebControls.Label lblext_mthd;
	protected global::System.Web.UI.WebControls.Label lblchinese;
	protected global::System.Web.UI.WebControls.Label lblresult;
	protected global::System.Web.UI.WebControls.Label lblunits;
	protected global::System.Web.UI.WebControls.Label lblref_flag;
	protected global::System.Web.UI.WebControls.Label lbllowvalue;
	protected global::System.Web.UI.WebControls.Label lblhighvalue;
	protected global::System.Web.UI.WebControls.Label lblprint_ref;
	protected global::System.Web.UI.WebControls.Label lblcheck_date;
	protected global::System.Web.UI.WebControls.Label lblcheck_by_name;
	protected global::System.Web.UI.WebControls.Label lblprnt_order;
	protected global::System.Web.UI.WebControls.Label lblIsDel;


       
    }
}
