//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace RuRo.Web.PatientDiagnose {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblid;
	protected global::System.Web.UI.WebControls.Label lblCardno;
	protected global::System.Web.UI.WebControls.Label lblCsrq00;
	protected global::System.Web.UI.WebControls.Label lblPatientName;
	protected global::System.Web.UI.WebControls.Label lblSex;
	protected global::System.Web.UI.WebControls.Label lblBrithday;
	protected global::System.Web.UI.WebControls.Label lblCardId;
	protected global::System.Web.UI.WebControls.Label lblTel;
	protected global::System.Web.UI.WebControls.Label lblRegisterNo;
	protected global::System.Web.UI.WebControls.Label lblIcd;
	protected global::System.Web.UI.WebControls.Label lblDiagnose;
	protected global::System.Web.UI.WebControls.Label lblType;
	protected global::System.Web.UI.WebControls.Label lblFlag;
	protected global::System.Web.UI.WebControls.Label lblDiagnoseDate;
	protected global::System.Web.UI.WebControls.Label lblIsDel;


       
    }
}
